kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-volume
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
